### ISSUE TITLE
Blog Index Page: Insights

### ISSUE THREAD

**Issue by YolineB** [LuskinOIC/website#224]
Add an insights section under Blogs

In Contentful, add option for Insights

**Comment by jaskim123** [comment]
Other item would be to fix the thumbnail images/some images inside the blog.

This link directs to some of these images that were mentioned to us having low  quality: https://www.dropbox.com/scl/fo/clsn4ozi245z5fn7qz26m/h?rlkey=nw077fhr8cf5upfvsa3zw6wjf&dl=0 
(this link also includes replacement images for some thumbnails/blog posts) Thank you. Let us know if you have any questions.

**Comment by YolineB** [comment]
Hi @jaskim123 could you confirm if the following items will be for the 'insights' section?

-5 Ways to keep your bones #healthy
-Treating Clubfoot w/ the Ponsetti Method..
-5 Common kids sports related injuries ....
-Four tips to get you through the clubfoot brace years

**Comment by YolineB** [comment]
I will move this link into issue #262 

> Other item would be to fix the thumbnail images/some images inside the blog.
> 
> This link directs to some of these images that were mentioned to us having low quality: https://www.dropbox.com/scl/fo/clsn4ozi245z5fn7qz26m/h?rlkey=nw077fhr8cf5upfvsa3zw6wjf&dl=0 (this link also includes replacement images for some thumbnails/blog posts) Thank you. Let us know if you have any questions.

**Comment by jaskim123** [comment]
Hi Yoline,

Thanks for checking up; confirming that yes, those articles will be placed in the ‘insights’ section.

Best,
Jason

Jason Kim │ Foundation<https://www.i2symbol.com/symbols/line>
Marketing Coordinator
403 W. Adams Blvd. │ Los Angeles, CA 90007
D: 213-742-1501 │M: 213-808-9888
***@***.******@***.***>
[logoemail]
Luskinoic.org

***@***.***<facebook.com/luskinoic>  ***@***.*** <twitter.com/luskinoic>   ***@***.*** <https://www.linkedin.com/school/orthopaedic-institute-for-children/>   ***@***.*** <instagram.com/luskinoic>   ***@***.*** <https://www.youtube.com/channel/UC3JqUFKs4TmQUGa9ekOYePA>   ***@***.*** <https://www.yelp.com/biz/orthopaedic-institute-for-children-los-angeles>
