### ISSUE TITLE
Implement Navigation Desktop

### ISSUE THREAD

**Issue by YolineB** [LuskinOIC/website#227]
### Implement updated style for nav bar, desktop

- [x] New dropdown area
- [x] white background
- [x] new logo
- [x] new donate
- [x] new save my spot 

<img width="500" alt="Pasted Graphic 2" src="https://github.com/LuskinOIC/website/assets/92892101/2e68d6c4-d6ab-4b5f-97fd-b7306c32b49e">

Nav Links:  

- [x] Patient Care: Patient Care Urgent Care Specialties MyChart Ambulatory Surgery Center Hemophilia Treatment Center Location 
- [x] Medical Professionals: For Medical Professionals Physicians Specialties Careers  
- [x] About: About Us Corporate Partnership International Children’s Program LuskinOIC Research Leadership Blog  
- [x] Ways to Give 
- [ ] Phone Number  

Search Container: User clicks icon, search bar drops down
<img width="500" alt="Pasted Graphic 3" src="https://github.com/LuskinOIC/website/assets/92892101/d13a5544-9633-43f0-8ef1-ad15c86eef5b">

**Comment by jaskim123** [comment]
Hello team,

Wanted to see if there was an update for this item?

Furthermore, as i'm not too well-versed with Github, I was curious if there is a feature where we can set a target date for items here?

**Comment by YolineB** [comment]
Hi @jaskim123 Jason, currently a work in progress! Below is the current status on my ticket. I can actually connect my branch to the issue too, so that you can better see the progress, apologies for not doing that sooner. Regarding a target date  I'm not seeing the option to mark it on the issue but we can detail it in the description / comments. My aim is to complete it by today.

<img width="400" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/59ba445f-5153-455e-921c-1dc2a6e08564">
