### ISSUE TITLE
Hand Trauma *Add Physician + Sports Med Copy Change

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#233]
![hand trauma](https://github.com/LuskinOIC/website/assets/148907402/bd22b057-0623-46e0-8ce2-493b4bb07cd8)

For Hand Trauma, we wanted to add Schaub to the list of providers for this section (both in specialty page and hand trauma page)

For Sports Med, this section:
![Sports Med](https://github.com/LuskinOIC/website/assets/148907402/72f4ae52-4894-40a2-b6a4-4059dfc1784e)

We would like to change to this copy:
![Sports_Med](https://github.com/LuskinOIC/website/assets/148907402/5a09ee04-d11f-4ecc-86a6-942f9de2a8d7)

Thank you!

**Comment by cpualei** [comment]
@jtorreggiani I completed this minor change unpublished in Contentful.

**Comment by YolineB** [comment]
Closing issue and publishing entry as it has been updated. 

Note: you can add a hyperlink to email using 'mailto:*insert email*' and 'tel:*insert number*'

<img width="323" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/ddce5256-0746-433b-bc4b-9ec2667f16e8">
