### ISSUE TITLE
Hover over article/Underline appears: Potential Changes?

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#234]
![Screenshot 2024-03-14 131636](https://github.com/LuskinOIC/website/assets/148907402/15bf44b1-30cf-4205-8faf-ac9a2d9fdee6)

When hovering over an article with the mouse, an underline appears; while funcitonal, we feel there could be a different hover effect then underlines. Would we be able to see a few suggestions?

**Comment by YolineB** [comment]
Hi @jaskim123 how about a title color change? When the user hovers, we can have just the title change into the luskin blue

**Comment by jaskim123** [comment]
That would work! As long as the blue is dark enough so it won't blend too much with the white.

**Comment by YolineB** [comment]
Closing as this issue has updated to issue #258
