### ISSUE TITLE
Changing Copy in Yellow Social Media Banner (Home Page)

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#235]
Hello! This would be just modifying the text in the social media banner here:
![Screenshot 2024-03-15 094824](https://github.com/LuskinOIC/website/assets/148907402/04fa1f3d-24e1-4b29-a062-0ed794cfb7bb)

Instead of 'Join us in our mission to transform musculoskeletal care for all kids, one child at a time, through education, research, and unwavering support.'

We would like 'Join us in our mission to provide outstanding services for all kids, one child at a time, through education and patient center care.'

Thank you!

**Comment by cpualei** [comment]
@jtorreggiani pushed the changes!

**Comment by jtorreggiani** [comment]
Fixes have been deployed. Closing this ticket!
