### ISSUE TITLE
Christine Caron, hiding her from physicians tab, creating new section.

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#236]
Hello team,

Currently we have christine Caron as part of the physicians in the 'physicians' page

![Screenshot 2024-03-15 131507](https://github.com/LuskinOIC/website/assets/148907402/f432a859-737d-4ad2-8b47-0d1b23d1bfbb)

Could we hide her, and create a third section in this page (underneath physciains/np's and pa's) titled 'Our Physical/Occupational Therapists'?

In this new section, it would be (Christine Caron first, then rest from A-Z):
- christine Caron
- Ruby Shin, OT (occupational therapist)
- Isaac Aguilar, PT, DPT ( Physical therapist)
- Sera Cho, PT (Physical therapist)
- Joanna De La Cruz, PT, DPT, OCS ,PCS (Physical therapist)
- Katelyn Ganev, PT (Physical Therapist)
- Mirna Guzman, PT (Physical Therapist)
- Mariana Lee, OT (occupational therapist)

The photos would be sent over later next week, so in the meantime we could have placeholder images. Thank you!

**Comment by jaskim123** [comment]
Update: I've 'archived' Christine Caron so she is not shown for now.

**Comment by YolineB** [comment]
@jaskim123 is there a specific list specialties for each of the PTs/OTs? 

In the meantime, we can list out their abbreviated qualifications

<img width="500" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/4f12eccc-8a11-4f4b-913d-bd7c94ad85a5">

**Comment by jaskim123** [comment]
Hi yoline,

No specified list, as they are mainly PTs/OTs. We can just list out their abbreviated qualifications for now.

**Comment by YolineB** [comment]
Added new section in Physician Bio 'PT/ OT' type.
