### ISSUE TITLE
Hand Surgery Card (Rank Change + Button Change)

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#246]
Hello team,

This assignment is split up into two tasks:
1. In our specialties page, we'd like to now move Hand Trauma right below where Clubfoot is.
2. We'd also like to change the title to 'Hand and Microsurgery Center'
3. For the area of buttons, is it possible for us to have two buttons; one that says' Trauma' and another saying 'Congenital/Microsurgery'?

Let me know if you have any questions.

Thank you.

**Comment by jaskim123** [comment]
Changed priority status, as we are currently taking a pause on this so your team would be able to work on fixing the blog page.

Thank you.

**Comment by jaskim123** [comment]
Update:

Can we have 'Congenital & Microsurgery' rather than 'Congenital/Microsurgery'?

Thank you!

**Comment by YolineB** [comment]
From our conversation on Monday, the specialty card for Hand and Microsurgery Center will stay consistent as the rest of the cards and remain as 'Patients'. Once the user (patient or provider) clicks, it will lead to the two pages with the two options.


<img width="500" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/238b3ad7-12bf-4019-b6a0-2acc2d2e6327">

<img width="500" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/d4584859-af1f-4296-a1e8-710dd6d5e9a1">


@jaskim123 please confirm when you get the chance, thank you!

**Comment by YolineB** [comment]
Re opening issue until we can review the changes in case of further changes needed. Once deployed, you can see the drafted changes in https://staging.luskinoic.org/hand-trauma/

**Comment by YolineB** [comment]
@cpualei if you would like to pick it up:

The Index Card Component that allows the user to switch between the two pages related to the hand surgery card needs a slight update. When the user clicks from the specialties index, the 'hand trauma' card should be automatically highlighted with the green border box. Currently, it only get highlighted after the user clicks between the two cards. 

![2024-04-17 15 31 36](https://github.com/LuskinOIC/website/assets/92892101/027718eb-1403-4000-843c-087731ca92d3)

**Comment by cpualei** [comment]
@YolineB I will add this to my to do list. Thanks!
