### ISSUE TITLE
Blog: Articles appear identical with one another

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#253]
Would be great to have each article identical with one another; we could have the majority of articles look like this: https://www.luskinoic.org/events/cerebral-palsy-summer-camp-2023/ as a start (more specifically noting the blue/white sections one after the other).

There are other articles with less information, such as this one: https://www.luskinoic.org/news/ucla-wbb-luskinoic-night/ 

Which is to say, we do not need the articles to look 100% identical; if there is way less information on certain articles we can leave it at that. As long as the blue/white sections and image placements look similar.

Let me know if you have any questions. Thank you!

**Comment by YolineB** [comment]
@jaskim123 I wanted to confirm that layout styles from Ilia's Figma. So far the styles would be consistent background and larger font size. Pictures would be in slideshow, or video layout.

**Comment by jaskim123** [comment]
@YolineB Hi Yoline; when it comes to the news/event paga article format, those look good to go. For Insights (the 5 ways to keep your bones healthy) example from Ilia's figma, we actually wantt o see if we can change the template for this in particular. We would like to:

1. no blue/white sections, just pure white
2. Have the option to still add images to the right or left side of text, or by itself as a section. I believe this is still possible, we would just need to either a. re-crop the current images we used or b. grab new ones? Let me know how i can help with this, if need be.

Overall we like what we currently have, we still would want to incorporate images into these kinds of articles.

**Comment by iliadeleon** [comment]
@jaskim123 We can definitely add full width  images, or the tri image component in between or anywhere within the post. 
If you would like to add images within this particular post, please send them. 

![Screenshot 2024-04-05 at 2 14 21 PM](https://github.com/LuskinOIC/website/assets/88496806/856c4e1b-5665-458c-85ad-f020438d232f)

**Comment by YolineB** [comment]
Hi @jaskim123 we can still have a two column layout. For the photos that you would like to incorporate, let's try at a minimum 480 x 480, with a max 768 x 560

**Comment by jaskim123** [comment]
Hi team,

We have someone (Clara) that works on Contentful for just creating blog pages. My assumption ( please correct me if i am mistaken) is that she could easily duplicate the templates we have by just 'creating a copy' of the blog that has that design template in place, and replacing the copy/pictures with the actual blog she would like to create.

With this being said, which live articles from news, events, and insights could we send to Clara so she could know to just press 'duplicate' on contentful to create that type of blog post?

**Comment by YolineB** [comment]
Hi @jaskim123, correct, you can copy the contentful entry, however the user should be careful changing the page section components/blog card as that will still be linked to the original article. The user can look at the page section components/blog as an example, but they should generate a new one page section with the appropriate page section type & new blog card.

For news:

- [LuskinOIC celebrates Dr. Bernthal](https://www.luskinoic.org/news/luskinoic-proudly-celebrates-dr-nicholas-m-bernthal-as-chair-of-the-ucla/)
- [Cerebral Palsy article](https://www.luskinoic.org/news/ucla-or-luskinoic-center-for-cerebral-palsy-margaret-jones-professional/) (Article with links and a three image component)
- [Trust Luskin Experts](https://www.luskinoic.org/news/trust-luskinoic-experts-to-diagnose-treat-and-manage-your-childs-scoliosis/) (Good for showing ordered lists, bolding, centered pictures, and a two column)

For events:
- [Toy and Joys](https://www.luskinoic.org/events/toys-and-joy/)

For Insights:

- [5 Common Kids Sports Related Injuries](https://www.luskinoic.org/insights/5-common-kids-sports-related-injuries-and-how-to-treat-them/)

**Comment by YolineB** [comment]
Closing this ticket as original articles have been updated. For further article requests, we will generate new issues.
