### ISSUE TITLE
Changing name 'physicians' to 'providers' + copying over to 'patient care' tab

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#259]
Hello team,

this item would be in the header section, the 'physicians' link underneath medical professionals
![physicians](https://github.com/LuskinOIC/website/assets/148907402/0dfd6369-174c-4af2-847d-f2488c83de31)

Could we change the name 'physicians' into 'providers'? This would be due to this list expanding from physicians to our np/pa's and PT's. 

Alongside this, it would be great to have 'providers' also located in the 'patient care' tab.

In terms of priority, would be great to start afetr the blogs.

**Comment by jaskim123** [comment]
Hello team,

Thank you for this; we do have just one more ask for this item. Could we also have 'physicians' located in the 'about' section?


This would also be a conversation for later (not now as there are a lot of current items), but to see if its possible to allow us to edit the header/footer/social media banner onto contentful.

**Comment by YolineB** [comment]
Added to the 'About' nav dropdown. You can add navbar sections by editing Navigation Navbar Types :

<img width="500" alt="image" src="https://github.com/LuskinOIC/website/assets/92892101/74da7a0f-43d0-42ac-93d3-492ce6bdf369">

Issue to add footer & social media banner onto contentful listed in issue #291
