### ISSUE TITLE
Re-organizing the Physicians/ NP's/PA cards in 'physciains' subpage

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#261]
Hello Team,

This assignment would be to reorganize the cards for both 'our physicians' and 'our nurse practitioners and physician's assistants'

**Physicians:**
Scaduto, Silva, Thompson, Quon, Bernthal, Schaub, Duffaut, Goldman, Honsvall,  Jones, Kang, Luck, Mckeever, Miller, Truong, Wright, Hoechlin, Wilson, Jones, Barad 

**PA's/NP's:**
Can we have Warnock first, then the rest can be in alphabetical order (last name) from A-Z?

As a note, we would like this priority to be higher than the blogs.
Thank you very much!

**Comment by YolineB** [comment]
@jaskim123 the physcians can now be ordered through Page > Physicians

**Comment by jaskim123** [comment]
Thank you so much!
