### ISSUE TITLE
Mailchimp to Hubspot signup

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#266]
![image](https://github.com/LuskinOIC/website/assets/148907402/4c29fc29-03fb-4fe7-b938-17fa9cb35099)
We have our newsletter signup here (which I believe directs to https://mailchi.mp/2da6d817803a/luskinoic-email-signup) . However, we are switching from mailchimp to hubspot, and we would like to redirect this submit button to: https://share.hsforms.com/1t977b2uBRnauBgzAZqGPfgqwu5b

I tried checking on Contentful to make this change, but did not find any section for ‘Join Our Newsletter’. Would we be able to implement this change? It says to embed this form, simply copy and paste the code below into the HTML code on your website.

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "45202079",
    formId: "b7defb6f-6b81-4676-ae06-0cc066a18f7e"
  });
</script>

Let me know if you have any questions. Thank you!

**Comment by YolineB** [comment]
@jaskim123 Could we get the hubspot login please?

**Comment by jaskim123** [comment]
I've added you and Joe T. as members to Hubspot just now, you can head to 'domains & URLs' by clicking top right to 'profile and preferences' from the profile icon, then bottom left side scrolling down.

**Comment by jaskim123** [comment]
Alongside this, would we be able to also include 'first name' and 'last name' fields onto this section?
