### ISSUE TITLE
Return to Sports Medicine Section + Page

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#270]
This assignment would be after the hand trauma pages/button assignment, whenever possible.

In our Sports Medicine Page: https://www.luskinoic.org/patient-care/specialties/sports-medicine/ , there is a section (highlighted below) that we’d like to add a small section that redirects to a new page.

 

![image](https://github.com/LuskinOIC/website/assets/148907402/1b087836-cb7e-48d3-be06-6020f3ef9afe)

1.	[This](url) section would be half the size of the blue section, as we are not having too much copy. Just copy, and a button leading to the new page. Here is the copy:
a.	Discover how LuskinOIC’s Sports Medicine team has revolutionized athletic recovery. Our team utilizes cutting-edge research to craft comprehensive testing protocols, assessing not just an athlete’s physical readiness, but also their psychological preparedness. From evaluating limb symmetry to analyzing neuromotor control, our expert physicians guide athletes and families toward a safe return to the sports and activities they love. At LuskinOIC, it’s not about fancy technology, but instead about accessible expertise, often provided free of charge, making us the top choice for an athlete to get back in the game.
2.	The button can be titled ‘Learn More’ to redirect them into a ‘Return to Sports Medicine’ page.
3.	The page itself has this copy:
________________________________________
ACL RETURN
TO SPORTS TESTING

Recovering from a knee injury or surgery can be difficult and frustrating,
especially when a younger athlete is  eager to return to sports and other activities.
Before an injured child gets back in the game, LuskinOIC’s Sports Medicine team
wants to ensure proper healing and recovery while also minimizing the risk of reinjury.

Using the most up-to-date research, the Sports
Medicine team has developed specific return-to-play criteria, including a series of physical
examinations and tests that determine if muscle strength and function has been restored
in the leg. Our expert staff evaluates form/technique, strength, agility, and symmetry of the
athlete’s legs. With this information, and after a discussion of each individual athlete’s goals for
returning to sports, we help educate patients and their families on how to safely and quickly
get back on the field!

WHY WE USE DIAGNOSTIC
ULTRASOUND FOR INJURIES
Ultrasound technology allows the medical staff at LuskinOIC’s Center for Sports
Medicine to evaluate and diagnose injuries quickly and painlessly, and the examination takes place right in the office. During the visit, our expert physicians can
visualize and analyze most muscle, tendon,and soft tissue injuries/concerns.
Diagnostic ultrasound costs much less than an MRI and often provides more detail for
certain injuries than a traditional MRI. Our physicians use the latest technology and techniques in diagnostic musculoskeletal ultrasound
and often teach these skills to other healthcare practitioners. Where other imaging
options require a patient to remain still, our patients can move their joints during the ultrasound
examination, allowing physicians to evaluate injuries dynamically during sport specific
movements, improving diagnosis and treatment options.

YOKOHAMA BASEBALL-9
(YB9) PROGRAM
Studies have shown that the Yokohama Baseball-9 Program helps prevent
elbow injuries and increases a shoulder’s range of motion.
This program consists of nine flexibility exercises focused on the wrist, elbow, shoulder, and hips.
________________________________________
4.	Here are some links to PDF’s that follow some parts of this copy, that we can hyperlink in certain areas of the page.
a.	[ACL Return to Sports Testing](https://www.dropbox.com/scl/fi/s1p7ixexxdziqayea4pcs/ACL-Return-To-Sports-Testing.pdf?rlkey=zs9j1djmn4qm9i8f60vww300a&dl=0)
b.	[Our Sports Medicine Specialists](https://www.dropbox.com/scl/fi/gq9qs8bi2q9bzke4drjkv/Our-Sports-Medicine-Super-Specialists.pdf?rlkey=mzyj3839akjd3k2kk6f5kh105&dl=0)
5.	Attached are some pictures we can use for this new page
![DSC_2158](https://github.com/LuskinOIC/website/assets/148907402/cac8faa3-4dd7-4609-bd80-830f140ba29c)
![King-Parker 1](https://github.com/LuskinOIC/website/assets/148907402/2d3ac5f2-fc14-460a-8f9f-910bbeb02d7c)
![OIC_Specialties_SportsMedicine_Hero_Petals_LARGE_MOBILE-2048x1777](https://github.com/LuskinOIC/website/assets/148907402/26b830c7-f868-4095-928a-e22b865557da)
![Soccer_IMG_5253](https://github.com/LuskinOIC/website/assets/148907402/4eba4284-b066-4315-a829-33357c29796b)

Let me know if you have any questions for this assignment, and when you believe you could start. Thank you!

**Comment by jaskim123** [comment]
@jtorreggiani Hi Joe, just wanted to add a comment that we have Caitlin running the assignment for Sports Medicine, as we believe this would be just populating on Contentful and not too code-based heavy, so Ilia Yoline and others may handle the Hand Trauma and other related tasks. Thanks!

**Comment by cpualei** [comment]
Hey @jaskim123 is there an already existing page that the "Learn More" button will link to or am I creating a new page with the info you mentioned?

**Comment by cpualei** [comment]
Hi @jtorreggiani and @YolineB, please review the following pages I made changes to:

Sports Medicine specialty page: [https://staging.luskinoic.org/patient-care/specialties/sports-medicine/](url)

Return to Sports Medicine (newly created): [https://staging.luskinoic.org/return-to-sports-medicine/](url)

Would love to get your opinions on the white/blue background colors for each section and if we should switch them around or not.

**Comment by jtorreggiani** [comment]
@cpualei, we reviewed the page and made a couple changes. Namely moving the download text into a button and aligning the images. There are some overarching challenges we have with large images like this. @jaskim123, I'm going to send over an email outline thing about how we can address the image sizing issues.

**Comment by jaskim123** [comment]
Hi team,

Wanted to give an update regarding these pages; Eunha and I have published these pages to make them live, but we can still work on updating the page. It's alright that people will notice some changes, as the copy will still remain the same, essentially. Thank you.

**Comment by YolineB** [comment]
Published, if more content/changes needed we can open a new issue.
