### ISSUE TITLE
Research page move to 'about' 

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#271]
Hello Team,

This assignment would be to add our research page on the 'about' and 'for medical professionals' section of our header.

**Comment by jaskim123** [comment]
Hi Team,

Wanted to actually move this to a high priority whenever possible. As an urgent ask, would this be doable by today?
https://www.luskinoic.org/research/

**Comment by YolineB** [comment]
Added to navbar, if you would like to move the order around you can do so in contentful ( [Navigation Dropdown - About
](https://app.contentful.com/spaces/e15v63h5asml/entries/9LzcZ0rTj9hizuVRQxyvK?previousEntries=4oHGBpQ13HkmG2jYmPFC9U&focusedField=navigationLinks) and [Navigation Dropdown - Medical Professionals](https://app.contentful.com/spaces/e15v63h5asml/entries/4Pgh1hTlmQPQqGOkNo3ycF?previousEntries=4oHGBpQ13HkmG2jYmPFC9U&focusedField=title) )
