### ISSUE TITLE
Change picture in 'physicians' header to updated photo

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#272]
Hello team,

This would be to simply replace our current photo of our doctors at the 'physciains' section for the header to this
![To meet our doctors](https://github.com/LuskinOIC/website/assets/148907402/8e1a11dc-78fe-4bed-9aea-cccd6f665957)

Thank you!

**Comment by iliadeleon** [comment]
In progress, but almost done. Just need to get the "Providers" title to show up on the thumbnail. 

<img width="1427" alt="Screenshot 2024-04-11 at 11 56 54 AM" src="https://github.com/LuskinOIC/website/assets/88496806/3e56e848-41d4-4eda-a6b8-da8171dec6e5">

**Comment by YolineB** [comment]
marking as completed, thank you @iliadeleon
