### ISSUE TITLE
Mobile + Header Change

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#278]
Hello Team,

From our previous conversation earlier today, for the mobile:
1. Increase size of the main slider carousel to be bigger than the urgent care photo, decrease size of urgent care.
2. Add the 'search' bar just like st.jude mobile.
3. Create 3 CTA buttons; (in priority): Save My Spot, Donate, MyChart (Please create so the hyperlinks on the buttons can be changed through contentful)
4. Decrease size of kulturecity logo
5. Spacing for Urgent care on mobile seems to be double spaced, while every other section on the home page seems to be single spaced. Please change so urgent care section is single-spaced.

Header Change:
1. On pause while Eunha and I discuss further.

Thank you!

**Comment by jaskim123** [comment]
As an update for this, instead of the 'mychart' CTA button for mobile, could it hyperlink to our hubspot newsletter? With title "Join Our Newsletter" (https://share.hsforms.com/1t977b2uBRnauBgzAZqGPfgqwu5b) 

Thank you!

**Comment by jaskim123** [comment]
Hi Joe,

Just wanted to say that we are a go for the Header Hover Changes. Thank you.

**Comment by YolineB** [comment]
> 1.Increase size of the main slider carousel to be bigger than the urgent care photo, decrease size of urgent care.

This will need a mobile layout option for carousel, moved to issue #315 . Size did decrease for urgent care card

✅ ~~2. Add the 'search' bar just like st.jude mobile.~~

✅ ~~3. Create 3 CTA buttons; (in priority): Save My Spot, Donate, MyChart (Please create so the hyperlinks on the buttons can be changed through contentful)~~

>4. Decrease size of kulturecity logo

We can decrease the size which will stay consistent in desktop and mobile, but if we want different sizes that will be a ticket #316

✅ ~~5. Spacing for Urgent care on mobile seems to be double spaced, while every other section on the home page seems to be single spaced. Please change so urgent care section is single-spaced.~~
