### ISSUE TITLE
Cerebral Palsy Event Article: video not in center

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#287]
Hi Team,

Small item; https://www.luskinoic.org/events/cerebral-palsy-professional-conference-and-family-forum-2024/
![image](https://github.com/LuskinOIC/website/assets/148907402/d4490927-0eb6-481f-b722-0e91e31dbda6)

Video seems to be off-center; I tried searching around in Contentful but couldn't find an option to move it to the middle.

Low priority.

**Comment by YolineB** [comment]
Selected 'full column' as there is no video w/ text.
