### ISSUE TITLE
Researchers Bio

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#295]
In our research page: https://www.luskinoic.org/research/

We have  8 researchers (one completed) that we would need to have their bio pages filled and to be clickable on the research page.

From priority:
Sang Hyun-Park, PhD (info: https://web.archive.org/web/20230321232040/https://luskinoic.org/sang-hyun-park-phd/)
Edward Ebramzadeh, PhD (info: https://web.archive.org/web/20230322005556/https://luskinoic.org/edward-ebramzadeh-phd/)
John Adams (info: https://web.archive.org/web/20230326163520/https://luskinoic.org/john-adams-md/)
Fabrizio Billi, PhD (https://web.archive.org/web/20230322004300/https://luskinoic.org/fabrizio-billi-phd/)
Daniel Cohn, PhD (https://web.archive.org/web/20230326153134/https://luskinoic.org/daniel-cohn-phd/)
Karen Lyons, PhD (https://web.archive.org/web/20230326145310/https://luskinoic.org/karen-lyons-phd/)
Eileen Fowler, PhD (https://web.archive.org/web/20230326160109/https://luskinoic.org/eileen-fowler-phd/)

**Comment by YolineB** [comment]
Progress Tracker:

- [ ] Sang Hyun-Park, PhD (info: https://web.archive.org/web/20230321232040/https://luskinoic.org/sang-hyun-park-phd/)
- [ ] Edward Ebramzadeh, PhD (info: https://web.archive.org/web/20230322005556/https://luskinoic.org/edward-ebramzadeh-phd/)
- [ ] John Adams (info: https://web.archive.org/web/20230326163520/https://luskinoic.org/john-adams-md/)
- [ ] Fabrizio Billi, PhD (https://web.archive.org/web/20230322004300/https://luskinoic.org/fabrizio-billi-phd/)
- [ ] Daniel Cohn, PhD (https://web.archive.org/web/20230326153134/https://luskinoic.org/daniel-cohn-phd/)
- [ ] Karen Lyons, PhD (https://web.archive.org/web/20230326145310/https://luskinoic.org/karen-lyons-phd/)
- [ ] Eileen Fowler, PhD (https://web.archive.org/web/20230326160109/https://luskinoic.org/eileen-fowler-phd/)
