### ISSUE TITLE
Sports Medicine Page Changes

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#304]
Hello Team,

1) In this page: https://www.luskinoic.org/return-to-sports-medicine/
Can we remove the last 3 sections, and just include the first section? (the section including the girl jumping on the left, and copy explaining 'return to sports testing' with a download button).

2) In this page: https://www.luskinoic.org/patient-care/specialties/sports-medicine/?tab=CommonConditionsandInjuries#CommonConditionsandInjuries 
In the tab 'Common Conditions And Injuries', can we actually copy/paste all the copy and move it into the 'recovery' tab?

![image](https://github.com/LuskinOIC/website/assets/148907402/79c0e4f3-0693-4de8-b106-4577252cc9dd)

We can place the copied text from common conditions and injuries _underneath_ the text we already have for recovery, like so:

![image](https://github.com/LuskinOIC/website/assets/148907402/6c66fe9e-e40b-4732-8148-46c68bef426e)

3) Also for the 'Common Conditions and Injuries' tab, can we just have all the hyperlinks ('Learn More/Watch our video') removed? Still keep the copy here.

**Comment by cpualei** [comment]
@jtorreggiani @YolineB
This issue is complete. I provided links to the staging site to review:

Return to Sports Medicine:
[https://staging.luskinoic.org/return-to-sports-medicine/](url)

Sports Medicine Patient Care Page:
[https://staging.luskinoic.org/patient-care/specialties/sports-medicine/?tab=CommonConditionsandInjuries#CommonConditionsandInjuries](url)

**Comment by YolineB** [comment]
Checked and published the components, thank you!

**Comment by jaskim123** [comment]
Hi @YolineB , don't wanna speak too soon but I see Return to Sports Medicine has the change, but Sports Medicine Patient Care Page remains the same  in the live site (although change is shown in staging). Wanted to double check that it's still in the process of publishing?

**Comment by YolineB** [comment]
Hi @jaskim123, that's right, we are manually triggering re-deployments through Digital Ocean - looking into that now

**Comment by YolineB** [comment]
Up and running! https://www.luskinoic.org/patient-care/specialties/sports-medicine/?tab=Recovery#Recovery

**Comment by jaskim123** [comment]
Hi @YolineB , while the recovery tab is updated, we actually meant to take a pause on removing the 'learn more' hyperlinks from the 'common conditions and injuries' tab. Would we be able to have the hyperlinks back by tomorrow?

**Comment by YolineB** [comment]
@jaskim123 do we want the hyper links in both the 'common conditions and injuries tab' and 'recovery' tab?

**Comment by jaskim123** [comment]
@YolineB  correct, just for now. Thank you.

**Comment by YolineB** [comment]
Hyper links added: https://www.luskinoic.org/patient-care/specialties/sports-medicine/?tab=CommonConditionsandInjuries
