### ISSUE TITLE
Moving Blog Post Section

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#308]
Hello team,

We're thinking of moving this section:
![image](https://github.com/LuskinOIC/website/assets/148907402/58de99cb-59db-402b-9ce5-59f3c5671aab)

in between where 'events' and 'patient stories' live. This would mean the news would be the very first section people look at, when headed to the blogs page (which makes a bit more sense)

**Comment by jtorreggiani** [comment]
This has been deployed. We will be making a follow up ticket to allow you to change this ordering in Contentful in the future.
