### ISSUE TITLE
Blogs Update

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#337]
Hello Team,

This request would be a current ask, as there are some new articles that might come up later on. 

_**EOTM/VOTM**_ (It's currently a WIP as a draft in contentful, but it would be great if we can pick it back up)

Essentially, we just want 2 columns; right side is for employee of the month (starting with latest, all the way down. You can check our IG to hyperlink, get a thumbnail, and see who was employee of the month),  and left side is for volunteer of the month (same deal).
 
We would like the main photo to be maybe a collage of 10-15 people who were votm/eotm, (black and white photos with a blue hue, text saying Volunteer/Employee of the Month. 
 
The main paragraph underneath can briefly explain (you can come up with a quick paragraph) how luskinoic likes to showcase our employees, what they’ve done for luskinoic as well as DTLA, and how we’re proud to have them as members. Check out some of our members below! Then right below that starts the 2 column with the employees/volunteers. 
 
 
LMK if you have any more questions regarding this. Thank you!

**_National Nurses Week_**
Video is here: https://youtu.be/89bmlfgWnJA 
Photos for slideshow is here: https://www.dropbox.com/scl/fo/xws5e56li8r2jwvidiw5g/ALNGYsoSoyPerEF-dIOsl_E?rlkey=7xa1ber3ld5nedko9ulgpuz3p&st=xqcw9ig9&dl=0 

Copy: 

Happy National Nurses Week! 🏥

We‘re thrilled to interview some of our amazing nurses at LuskinOIC and showcase our Urgent Care. Thank you all for your hard work in ensuring all children in Downtown Los Angeles receive expert orthpaedic care, regardless of financial circumstances. LuskinOIC is proud to be the only orthopaedic urgent care in the country.

**Comment by jaskim123** [comment]
Hi @iliadeleon  , thank you for this! Below are my answers:

1. Unfortunately I do not; by a group photo however, do you mean just a group photo of volunteers?
2. For rows instead of columns,  looks good! As we would be updating each month, more and more cards will be added on to the rows. Are we thinking maybe we can have a 'see more' button for EOTM/VOTM, and the first 6 (for example) months we see are the most updated VOTM/EOTMs? the 'see more' can redirect to the full list of employees/volunteers. What do you think?
3. blog looks great! Thank you, Ilia.
4. That would be great; I believe we have a meeting today? If so, it would be great if I could take a look.

**Comment by iliadeleon** [comment]
Hi @jaskim123 

1. Will wait for a picture of either Employees or Volunteers, also please let me know what can be used as the blog card thumbnail. 
2. Discussed in the meeting, will stop it at 6 cards and have a See More button- either dropping down or leading to a separate "Past EOTM/VOTM" page.
3. Will just wait for the images to publish

**Comment by jaskim123** [comment]
1. We could use this https://www.dropbox.com/scl/fi/13ioyy2vs5kxo6wridsm7/DSC_2577.JPG?rlkey=x1q5h89brad9anzu3k1rddvz7&st=hsxfih9d&dl=0 for the hero, and the thumbnail can be this I think? https://www.dropbox.com/scl/fi/i68zaawp4bl6i9v6wnzak/DSC_2573.JPG?rlkey=voqyeieaobkozs8i411c9e3li&st=5ead3lqq&dl=0 We just may have to crop the photo a bit to fit ( which I think would be easier for a vertical photo)
2. Sounds good
3. Awesome!

**Comment by iliadeleon** [comment]
@jaskim123 This has been published. 

https://www.luskinoic.org/news/volunteer-of-the-month-employee-of-the-month-highlights/
